# Generated by Django 5.2.7 on 2025-10-25 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название отчета')),
                ('report_type', models.CharField(choices=[('defect', 'Отчет по дефектам'), ('project', 'Отчет по проектам'), ('user', 'Отчет по пользователям'), ('custom', 'Пользовательский отчет')], max_length=20, verbose_name='Тип отчета')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Дата с')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата по')),
                ('status_filter', models.CharField(blank=True, max_length=20, verbose_name='Фильтр по статусу')),
                ('priority_filter', models.CharField(blank=True, max_length=20, verbose_name='Фильтр по приоритету')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Шаблон отчета',
                'verbose_name_plural': 'Шаблоны отчетов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации')),
                ('file_format', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('csv', 'CSV'), ('excel', 'Excel')], default='html', max_length=10, verbose_name='Формат')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/', verbose_name='Файл отчета')),
                ('parameters', models.JSONField(default=dict, verbose_name='Параметры отчета')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сгенерировал')),
                ('report_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate', verbose_name='Шаблон отчета')),
            ],
            options={
                'verbose_name': 'Сохраненный отчет',
                'verbose_name_plural': 'Сохраненные отчеты',
                'ordering': ['-generated_at'],
            },
        ),
    ]
